name: quick_drop2
description: Delivery app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  # Update the twilio_flutter package to version 0.0.9 or the compatible version
  twilio_flutter: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add your images to the assets section
  assets:
    - inropng/app3.png
    - assets/flightcontroller.png
    - assets/kk2.1.5board.png
    - assets/gpsmodule.png
    - assets/arduinoboard.png
    - assets/raspberrypi.png
    - assets/battery.png
    - assets/tablet.png
    - assets/smartphone.png
    - assets/transistor.png
    - assets/esp.png
    - assets/expo.jpg
    - assets/New Project.png